### ISSUE TITLE
Likly me...

### ISSUE THREAD

**Issue by Bishop-trevorstuart** [kejonaMC/GeyserUpdater#84]
This is myself having an issue, but I couldn't join the discord and saw no where else to request assistance. 
I have waterfall running and the geyserupdater. It pulls updates, and then kills the server. 
Your page says I need an auto-restart script, but there is also an auto-generated script. 
All I really need to understand is where/when to run this script? Do I adjust the config.yml to somehow use the restart script? Or is the script supposed to be used by the OS? I'm running MineOS, so if it's run by the OS somehow I have to figure out how to start a server with different commands, but I just need to know the direction to point.

Thanks!

**Comment by Jens-Co** [comment]
Hi there!

first of all this is our discord link https://discord.gg/ZBS7JBjw or you could also click the discord badge on the readme of this Github repo.
Second; once you enabled the generate script in our config.yml and restarted the server a custom restart script should have been generated. The only thing you need to do is run that generated script, you can delete your original script and just replace it with ours :) Our script has a restart loop so everytime the server stops due to GeyserUpdate it will automatically restart your server. If you need further assistance you can always join our discord.

Jens

**Comment by Konicai** [comment]
If you're running mineos I would assume that it restarts the server automatically when it shutsdown, in which case you don't need a restart script
